# Generated by Django 5.1.3 on 2024-11-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamajMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamajMemberEducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.city')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to='survey.samajmember')),
            ],
        ),
        migrations.CreateModel(
            name='SamajMemberEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='survey.samajmember')),
            ],
        ),
        migrations.CreateModel(
            name='SamajMemberIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_members', models.PositiveIntegerField()),
                ('other_members', models.PositiveIntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='survey.samajmember')),
            ],
        ),
        migrations.CreateModel(
            name='SamajMemberMobileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_numbers', to='survey.samajmember')),
            ],
        ),
        migrations.CreateModel(
            name='SamajMemberOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('occupation_type', models.CharField(choices=[('Business', 'Business'), ('Service', 'Service'), ('Self Employed', 'Self Employed'), ('Government Job', 'Government Job')], max_length=20)),
                ('occupation_name', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='survey.samajmember')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='survey.country')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='survey.state')),
            ],
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='survey.district')),
            ],
        ),
        migrations.CreateModel(
            name='SamajMemberAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no_building', models.CharField(max_length=100)),
                ('street_landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.district')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='survey.samajmember')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.state')),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.taluka')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='survey.taluka'),
        ),
    ]
