# Generated by Django 5.1.3 on 2024-11-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_samajmember_created_at_samajmember_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samajmemberaddress',
            name='taluka',
        ),
        migrations.RemoveField(
            model_name='city',
            name='taluka',
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='survey.district'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.state'),
        ),
        migrations.DeleteModel(
            name='Taluka',
        ),
    ]
