# Generated by Django 5.1.3 on 2025-03-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_samajmemberoccupation_company_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajmembereducationalqualification',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
