# Generated by Django 5.1.3 on 2025-03-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_taluka'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajmemberaddress',
            name='taluka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.taluka'),
        ),
    ]
