# Generated by Django 5.1.3 on 2025-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_samajmemberaddress_taluka'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajmember',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
