# Generated by Django 5.1.3 on 2025-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_samajmember_guardian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samajmembereducationalqualification',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samajmembereducationalqualification',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
