# Generated by Django 5.1.3 on 2025-08-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_samajmember_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajmemberaddress',
            name='address_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Correspondence', 'Correspondence')], default='Permanent', max_length=20),
        ),
    ]
